all: 
	gcc 1-czesc.c -o 1-czesc.bin
	gcc 2-zmienne.c -o 2-zmienne.bin
	gcc 3-operatory.c -o 3-operatory.bin
	gcc 4-warunki.c -o 4-warunki.bin
	gcc 5-petle.c -o 5-petle.bin
	gcc 6-funkcje.c -o 6-funkcje.bin
	gcc 7-logika.c -o 7-logika.bin
	gcc 8-struktury.c -o 8-struktury.bin
	gcc 9-tablice.c -o 9-tablice.bin

clean:
	rm  *.bin

