all: 
	gcc 1-hello.c -o 1-hello.bin
	gcc 2-variables.c -o 2-variables.bin
	gcc 3-operators.c -o 3-operators.bin
	gcc 4-conditionals.c -o 4-conditionals.bin
	gcc 5-loops.c -o 5-loops.bin
	gcc 6-functions.c -o 6-functions.bin
	gcc 7-logic.c -o 7-logic.bin
	gcc 8-structures.c -o 8-structures.bin
	gcc 9-arrays.c -o 9-arrays.bin

clean:
	rm  *.bin

