all:	 
	gcc 1-hello.cpp -o 1-hello.bin
	gcc 2-variables.cpp -o 2-variables.bin
	gcc 3-operators.cpp -o 3-operators.bin
	gcc 4-conditionals.cpp -o 4-conditionals.bin
	gcc 5-loops.cpp -o 5-loops.bin
	gcc 6-functions.cpp -o 6-functions.bin
	gcc 7-logic.cpp -o 7-logic.bin
	gcc 8-structures.cpp -o 8-structures.bin
	gcc 9-arrays.cpp -o 9-arrays.bin

clean:
	rm  *.bin

