all: 
	gcc 1-hello.cpp -o 1-hello.bin
	gcc 2-variables.cpp -o 2-variables.bin
	gcc 3-operatory.cpp -o 3-operatory.bin
	gcc 4-warunki.cpp -o 4-warunki.bin
	gcc 5-petle.cpp -o 5-petle.bin
	gcc 6-funkcje.cpp -o 6-funkcje.bin
	gcc 7-logika.cpp -o 7-logika.bin
	gcc 8-struktury.cpp -o 8-struktury.bin
	gcc 9-tablice.cpp -o 9-tablice.bin

clean:
	rm  *.bin

