all: 
	rustc 1-hello.rs -o 1-hello.bin
	rustc 2-variables.rs -o 2-variables.bin
	rustc 3-operators.rs -o 3-operators.bin
	rustc 4-conditionals.rs -o 4-conditionals.bin
	rustc 5-loops.rs -o 5-loops.bin
	rustc 6-functions.rs -o 6-functions.bin
	rustc 7-logic.rs -o 7-logic.bin
	rustc 8-structures.rs -o 8-structures.bin
	rustc 9-arrays.rs -o 9-arrays.bin

clean:
	rm  *.bin

